= Get started with Build Your Docker Images Automatically When You Push on GitHub

:toc:


A comprehensive hands-on tutorial explaining building docker image when images are push on github

== Create Your GitHub Repo and Add a Dockerfile

. The first step is, obviously, to setup your repository on GitHub

	cd ~
+

	MacBook-Pro-de-Lakdar-2:ContainersGen lakdar$ git clone https://github.com/gitex2018/dockerbuild.git
	Cloning into 'dockerbuild'...
	warning: You appear to have cloned an empty repository.
	MacBook-Pro-de-Lakdar-2:ContainersGen lakdar$ ls
	README.md   desktopApp  dockerbuild readme.adoc
	MacBook-Pro-de-Lakdar-2:ContainersGen lakdar$ cd dockerbuild/
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ ls
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ echo "FROM hellow-world" > Dockerfile
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ git add Dockerfile
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ git commit -m "Initial import"
	[master (root-commit) 46b38cb] Initial import
 	1 file changed, 1 insertion(+)
 	create mode 100644 Dockerfile
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ git push
	Username for 'https://github.com': gitex2018
	Password for 'https://gitex2018@github.com':
	Enumerating objects: 3, done.
	Counting objects: 100% (3/3), done.
	Writing objects: 100% (3/3), 232 bytes | 232.00 KiB/s, done.
	Total 3 (delta 0), reused 0 (delta 0)
	To https://github.com/gitex2018/dockerbuild.git
 	* [new branch]      master -> master
	MacBook-Pro-de-Lakdar-2:dockerbuild lakdar$ ls
	Dockerfile

+

. Enabling Automated Builds on Docker Hub

To enable automated builds you need to connect your Docker Hub account with your account on GitHub. Login to Docker Hub and go to Account Settings > Linked Accounts. Scroll-down to find GitHub and click on the Connect link. You will be taken through the usual OAuth process where you login to GitHub (if not already logged-in) and authorise Docker to access your GitHub repositories. If everything goes well, you should receive a notification from GitHub:


== References

. https://medium.com/better-programming/build-your-docker-images-automatically-when-you-push-on-github-18e80ece76af


